
name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - netcdf4
  - xarray
  - pillow
  - pandas
  - hdf4
  - hdf5
  - ffmpeg
  - imageio
  - rise
  
